pipeline:
  test:
    image: django:1.9.7-python3
    commands:
      - cd nlsub
      - pip install -r requirements.txt
      - for i in 1 2 3 4 5; do ./manage.py check && break || sleep 5; done
      - ./manage.py migrate
      - ./manage.py test
  backend:
    image: plugins/docker
    repo: nielsole/nl-subscription
    username: ${DRONE_USERNAME}
    password: ${DRONE_PASSWORD}
    tags:
      - dev

services:
  db:
    image: postgres:9.4.5